version: '3'
services:
  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - .:/app
    networks:
      - pa_vcid_netz
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: pa_vcid_db
    networks:
      - pa_vcid_netz
    ports:
      - "5432:5432"
    expose:
      - "5432"
networks:
  pa_vcid_netz:
    driver: bridge
